### ISSUE TITLE
v14 (and v15) now requires icon dependencies

### ISSUE THREAD

**Issue by janpapenbrock** [MurhafSousli/ngx-sharebuttons#673]
Hey there, thanks for your work on this project!

#### The issue

I've just upgraded from v13 to v14 and am now seeing compiler errors:

```
./node_modules/ngx-sharebuttons/fesm2022/ngx-sharebuttons-icons.mjs:2:0-65 - Error: Module not found: Error: Can't resolve '@fortawesome/angular-fontawesome' in '/my-project/node_modules/ngx-sharebuttons/fesm2022'

./node_modules/ngx-sharebuttons/fesm2022/ngx-sharebuttons-icons.mjs:3:0-218 - Error: Module not found: Error: Can't resolve '@fortawesome/free-brands-svg-icons' in '/my-project/node_modules/ngx-sharebuttons/fesm2022'

./node_modules/ngx-sharebuttons/fesm2022/ngx-sharebuttons-icons.mjs:4:0-133 - Error: Module not found: Error: Can't resolve '@fortawesome/free-solid-svg-icons' in '/my-project/node_modules/ngx-sharebuttons/fesm2022'
```

I switched from `SharedModule` to `SharedButtonDirective`. I bring my own icons instead of using any of the provided icons.

#### Reproduction

I have reproduced the error with v15, too, on a fresh Angular v18 installation. I've pushed this as a repository here: https://github.com/janpapenbrock/ngx-sharebuttons-angular-18.

I basically followed this Wiki page (first usage example without icons): https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Share-Button-Directive

This is the component: https://github.com/janpapenbrock/ngx-sharebuttons-angular-18/blob/main/src/app/app.component.ts

#### Error output

```
✘ [ERROR] Could not resolve "@fortawesome/angular-fontawesome"

    node_modules/ngx-sharebuttons/fesm2022/ngx-sharebuttons-icons.mjs:2:30:
      2 │ import { FaIconLibrary } from '@fortawesome/angular-fontawesome';
        ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@fortawesome/angular-fontawesome" as external to exclude it from the
  bundle, which will remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@fortawesome/free-brands-svg-icons"

    node_modules/ngx-sharebuttons/fesm2022/ngx-sharebuttons-icons.mjs:3:181:
      3 │ ...okMessenger, faTelegramPlane, faMix, faXing, faLine } from '@fortawesome/free-brands-svg-icons';
        ╵                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@fortawesome/free-brands-svg-icons" as external to exclude it from the
  bundle, which will remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@fortawesome/free-solid-svg-icons"

    node_modules/ngx-sharebuttons/fesm2022/ngx-sharebuttons-icons.mjs:4:97:
      4 │ ...faPrint, faExclamation, faLink, faEllipsisH, faMinus } from '@fortawesome/free-solid-svg-icons';
        ╵                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@fortawesome/free-solid-svg-icons" as external to exclude it from the
  bundle, which will remove this error and leave the unresolved path in the bundle.
```

#### Context

I don't see why the icons module should even be compiled, as I'm not using the icons at all.

Also wondering whether there maybe are (peer?) dependencies missing in this file: https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/ngx-sharebuttons/package.json?

#### Environment

- Angular: v17 / v18
- ngx-sharebuttons: v14 / v15
- Browser(s): n/a
- Operating System (e.g. Windows, macOS, Ubuntu): Linux

**Comment by MurhafSousli** [comment]
I realized that in the new version we are using only the interface `IconProp` from the core package `@fortawesome/fontawesome-svg-core`, What I can do is added as the package dependency, this way it will be installed when you install `npm i ngx-sharebuttons` but no code is added, only an interface.

Could you try `npm i @fortawesome/fontawesome-svg-core` and see if the error goes away?

**Comment by MurhafSousli** [comment]
The problem is the icons package is being bundled even when not being used, I opened an issue to learn what is wrong https://github.com/ng-packagr/ng-packagr/issues/2860

**Comment by janpapenbrock** [comment]
Looked into it a bit more, and it seems it is this import chain that leads to the packages being required:

1. `SharedButtonDirective` imports `ShareService` in https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/ngx-sharebuttons/src/lib/share-button.directive.ts#L19
2. `ShareService` imports `SHARE_ICONS` from `ngx-sharebuttons/icons` in https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/ngx-sharebuttons/src/lib/share.service.ts#L7C30-L7C52
3. `SHARE_ICONS` imports all three `@fortawesome/...` dependencies in https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/ngx-sharebuttons/icons/src/share-icons.ts

**Comment by MurhafSousli** [comment]
Whoops, good catch! I didn't notice that imports.

**Comment by MurhafSousli** [comment]
We are still using `IconProp` interface from **FontAwesome**.

 https://github.com/MurhafSousli/ngx-sharebuttons/blob/30c35371ea1b6d7e0ad67844ab9d62f0963ab396/projects/ngx-sharebuttons/src/lib/share-button.directive.ts#L17

I added it as a `dependency`

https://github.com/MurhafSousli/ngx-sharebuttons/blob/916105cba32594d76e0e60c68777b34dc58bce48/projects/ngx-sharebuttons/package.json#L1-L14

This mean the package will be install behind the seen without the need to install it manually, is that fine?

**Comment by janpapenbrock** [comment]
Thanks! I just tried it, works :+1: 

--

I believe though that the dependency is not really necessary for just importing that type information in the directive, as it will not be included in the compilation anyways, so I believe it would not fail even if I did not have that dependency installed.

You could also write this which would make it more explicit, I belive:

`import type { IconProp } from '@fortawesome/fontawesome-svg-core'; ` 

Looking at the compiled directive seems to confirm this:

```
import { Directive, Input, Output, HostListener, inject, signal, effect, computed, input, EventEmitter, ElementRef } from '@angular/core';
import { ShareService } from './share.service';
import { SHARE_BUTTONS_CONFIG, } from './share.models';
import { DEFAULT_OPTIONS, SHARE_BUTTONS } from './share.defaults';
import { SHARE_BUTTONS_PROP } from './custom-share-button-provider';
import * as i0 from "@angular/core";
export class ShareButtonDirective {
```

The import from the external package does not show up. So I guess just splitting out the injection token would do the trick here.

But regardless of which solution you choose, great to see this working with the next release :)

**Comment by MurhafSousli** [comment]
@janpapenbrock I used the `type` imports and removed the dependency, could you try 15.0.1 and see if that works.

**Comment by janpapenbrock** [comment]
Works, thanks a lot!

**Comment by jcrespoven** [comment]
Hi @MurhafSousli , sorry to reopen this, but it seems that I'm experiencing the same problem as @janpapenbrock with version 15.0.2. I'm trying to use ShareButtonDirective with no icon but the following compilation error is being shown:

```
Error: node_modules/ngx-sharebuttons/lib/share-button.directive.d.ts:2:31 - error TS2307: Cannot find module '@fortawesome/fontawesome-svg-core' or its corresponding type declarations.

import type { IconProp } from '@fortawesome/fontawesome-svg-core';
```
I've just installed ngx-sharebuttons (`npm i ngx-sharebuttons`) and checked that no font-awesome dependencies where installed in the process (btw, I don't need them).

**Comment by sqrter** [comment]
The problem is still there in 15.0.3

<img width="654" alt="image" src="https://github.com/user-attachments/assets/fc7f1631-884f-47ff-9f5d-3028d98ad0e6">

**Comment by Oussemasahbeni** [comment]
Im experiencing the same problem usinga angular  18.0.1 and  ngx-sharebuttons 15.0.3

**Comment by Oussemasahbeni** [comment]
any updates on this issue ?

**Comment by MurhafSousli** [comment]
Removed the interface from the directive package in v15.0.4

**Comment by Oussemasahbeni** [comment]
![image](https://github.com/user-attachments/assets/ed2e4774-c201-4a77-9cbd-4d0225287468)
i got this error after upgrading to the new version

**Comment by MurhafSousli** [comment]
@Oussemasahbeni Try v15.0.6

**Comment by Oussemasahbeni** [comment]
It works fine after upgrading to v15.0.6, thank you for your help
